name: Next.js EC2 Direct Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # Connect to EC2 and deploy
      - name: Deploy Application on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            # Go to home directory
            cd /home/ec2-user

            # Clone repo if not exists
            if [ ! -d "react-app" ]; then
              git clone https://github.com/Vivek9307/demo-repo.git
            fi

            # Go to project directory
            cd react-app

            # Pull latest code
            git pull origin main

            # Install Node.js dependencies
            npm install

            # Build Next.js application
            npm run build

            # Stop old app
            npm run dev

          
