name: Next.js EC2 Deployment

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      # Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build Next.js application
      - name: Build Application
        run: npm run build

      # Create tar package
      - name: Create Artifact Package
        run: |
          tar -czf app.tar.gz \
            .next \
            package.json \
            next.config.js

      # Upload artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: app.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      # Download artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build

      # Copy tar file to EC2
      - name: Copy Artifact to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app.tar.gz"
          target: "/tmp"

      # Deploy application
      - name: Deploy Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            # Create app directory
            sudo mkdir -p /var/www/react-app

            # Give permissions
            sudo chown -R ec2-user:ec2-user /var/www/react-app

            # Remove old deployment
            rm -rf /var/www/react-app/.next
            rm -rf /var/www/react-app/public

            # Extract new build
            tar -xzf /tmp/app.tar.gz -C /var/www/react-app

            # Go to app directory
            cd /var/www/react-app

        

      # Restart nginx
      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
